id: P005466
initial_creation_type: ocr
created_at: 23/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W2CZ6598
  title: རས་ཆུང་རྡོ་རྗེ་གྲགས་པའི་རྣམ་ཐར
  author: ''
  volumes:
    9812f9fda82245f1a1ef6bf5affd0593:
      image_group_id: I1KG1411
      title: ''
      volume_number: 1
      total_pages: 596
      base_file: v001.txt
