id: I7950DF14
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-23T02:47:09+00:00'
last_modified: '2022-06-08T03:17:05.363227+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W2CZ6598
  title: རས་ཆུང་རྡོ་རྗེ་གྲགས་པའི་རྣམ་ཐར
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    FD2B:
      image_group_id: I1KG1411
      title: ''
      total_pages: 596
      order: 1
      base_file: FD2B.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
